version: "3.8"

services:
    server:
        image: boxial:client-server
        container: boxial-client-server
        networks:
            - frontend
        build:
            context: src/server
            dockerfile: config/Dockerfile.server
    frontend:
        image: boxial:client-frontend
        container: boxial-client-frontend
        networks:
            - frontend
        build: 
            context: src/frontend
            dockerfile: config/Dockerfile.frontend
    backend:
        image: boxial:client-backend
        container: boxial-client-backend
        networks:
            - frontend
            - backend
        build: 
            context: src/backend
            dockerfile: config/Dockerfile.backend
        ports: 
            - "6001:3000"
        environment:
            - NODE_PORT=3000
    database:
        image: mongo
        container: boxial-client-database
        environment:
            MONGO_INITDB_ROOT_USERNAME: none
            MONGO_INITDB_ROOT_PASSWORD: none
        networks:
            - backend
        restart: on-failure
        volumes:
            - ${PWD}/mongo:/data/db        

networks:
    frontend:
        driver: bridge         
    backend:
        driver: bridge